"""create all tables

Revision ID: 343bdbf5a71d
Revises: 009414521c7d
Create Date: 2026-09-27 23:25:35.499594
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '343bdbf5a71d'
down_revision: Union[str, None] = '009414521c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_id'), 'ai_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_trip_id'), 'ai_conversations', ['trip_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('itinerary_days',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_days_id'), 'itinerary_days', ['id'], unique=False)
    op.create_index(op.f('ix_itinerary_days_trip_id'), 'itinerary_days', ['trip_id'], unique=False)
    op.create_table('packing_lists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packing_lists_id'), 'packing_lists', ['id'], unique=False)
    op.create_index(op.f('ix_packing_lists_trip_id'), 'packing_lists', ['trip_id'], unique=False)
    op.create_table('place_photos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_photos_id'), 'place_photos', ['id'], unique=False)
    op.create_index(op.f('ix_place_photos_place_id'), 'place_photos', ['place_id'], unique=False)
    op.create_table('place_tips',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('BEST_TIME', 'SAFETY', 'CLOTHING', 'TRANSPORT', 'MONEY', 'FOOD', 'GENERAL', name='place_tip_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_tips_id'), 'place_tips', ['id'], unique=False)
    op.create_index(op.f('ix_place_tips_place_id'), 'place_tips', ['place_id'], unique=False)
    op.create_table('trip_members',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', name='trip_member_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_members_id'), 'trip_members', ['id'], unique=False)
    op.create_index(op.f('ix_trip_members_trip_id'), 'trip_members', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trip_members_user_id'), 'trip_members', ['user_id'], unique=False)
    op.create_table('trip_wallets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_wallets_id'), 'trip_wallets', ['id'], unique=False)
    op.create_index(op.f('ix_trip_wallets_trip_id'), 'trip_wallets', ['trip_id'], unique=False)
    op.create_table('ai_extractions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('screenshot_id', sa.BigInteger(), nullable=True),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum(name='ai_extraction_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['screenshot_id'], ['screenshots.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_extractions_document_id'), 'ai_extractions', ['document_id'], unique=False)
    op.create_index(op.f('ix_ai_extractions_id'), 'ai_extractions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_extractions_screenshot_id'), 'ai_extractions', ['screenshot_id'], unique=False)
    op.create_index(op.f('ix_ai_extractions_trip_id'), 'ai_extractions', ['trip_id'], unique=False)
    op.create_index(op.f('ix_ai_extractions_user_id'), 'ai_extractions', ['user_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='ai_message_role'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_messages_id'), 'ai_messages', ['id'], unique=False)
    op.create_table('budget_categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('budget_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_categories_budget_id'), 'budget_categories', ['budget_id'], unique=False)
    op.create_index(op.f('ix_budget_categories_id'), 'budget_categories', ['id'], unique=False)
    op.create_table('checklist_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('checklist_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_checklist_id'), 'checklist_items', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_checklist_items_id'), 'checklist_items', ['id'], unique=False)
    op.create_table('itinerary_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('itinerary_day_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('type', sa.Enum('ACTIVITY', 'FOOD', 'TRANSPORT', 'HOTEL', 'FREE_TIME', 'OTHER', name='itinerary_item_type'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'COMPLETED', 'CANCELLED', name='itinerary_item_status'), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_day_id'], ['itinerary_days.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_items_id'), 'itinerary_items', ['id'], unique=False)
    op.create_index(op.f('ix_itinerary_items_itinerary_day_id'), 'itinerary_items', ['itinerary_day_id'], unique=False)
    op.create_index(op.f('ix_itinerary_items_place_id'), 'itinerary_items', ['place_id'], unique=False)
    op.create_table('memory_photos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('memory_id', sa.BigInteger(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_photos_id'), 'memory_photos', ['id'], unique=False)
    op.create_index(op.f('ix_memory_photos_memory_id'), 'memory_photos', ['memory_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', name='wallet_transaction_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['trip_wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_table('expense_splits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('expense_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_splits_expense_id'), 'expense_splits', ['expense_id'], unique=False)
    op.create_index(op.f('ix_expense_splits_id'), 'expense_splits', ['id'], unique=False)
    op.create_index(op.f('ix_expense_splits_user_id'), 'expense_splits', ['user_id'], unique=False)
    op.add_column('accommodations', sa.Column('trip_id', sa.BigInteger(), nullable=False))
    op.add_column('accommodations', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('accommodations', sa.Column('check_in', sa.DateTime(), nullable=False))
    op.add_column('accommodations', sa.Column('check_out', sa.DateTime(), nullable=False))
    op.add_column('accommodations', sa.Column('room_type', sa.String(length=100), nullable=True))
    op.add_column('accommodations', sa.Column('confirmation_number', sa.String(length=255), nullable=True))
    op.add_column('accommodations', sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('accommodations', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('accommodations', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('accommodations', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_accommodations_name'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_user_id'), table_name='accommodations')
    op.create_index(op.f('ix_accommodations_trip_id'), 'accommodations', ['trip_id'], unique=False)
    op.drop_constraint(op.f('accommodations_user_id_fkey'), 'accommodations', type_='foreignkey')
    op.create_foreign_key(None, 'accommodations', 'trips', ['trip_id'], ['id'])
    op.drop_column('accommodations', 'user_id')
    op.drop_column('accommodations', 'created_at')
    op.drop_column('accommodations', 'data')
    op.drop_column('accommodations', 'description')
    op.add_column('budgets', sa.Column('trip_id', sa.BigInteger(), nullable=False))
    op.add_column('budgets', sa.Column('total_budget', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('budgets', sa.Column('saved_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('budgets', sa.Column('spent_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('budgets', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('budgets', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('budgets', 'currency',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_budgets_name'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.create_index(op.f('ix_budgets_trip_id'), 'budgets', ['trip_id'], unique=False)
    op.drop_constraint(op.f('budgets_user_id_fkey'), 'budgets', type_='foreignkey')
    op.create_foreign_key(None, 'budgets', 'trips', ['trip_id'], ['id'])
    op.drop_column('budgets', 'amount')
    op.drop_column('budgets', 'user_id')
    op.drop_column('budgets', 'name')
    op.drop_column('budgets', 'description')
    op.drop_column('budgets', 'data')
    op.add_column('checklists', sa.Column('trip_id', sa.BigInteger(), nullable=False))
    op.add_column('checklists', sa.Column('title', sa.String(length=255), nullable=False))
    op.alter_column('checklists', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_checklists_name'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_user_id'), table_name='checklists')
    op.create_index(op.f('ix_checklists_trip_id'), 'checklists', ['trip_id'], unique=False)
    op.drop_constraint(op.f('checklists_user_id_fkey'), 'checklists', type_='foreignkey')
    op.create_foreign_key(None, 'checklists', 'trips', ['trip_id'], ['id'])
    op.drop_column('checklists', 'user_id')
    op.drop_column('checklists', 'description')
    op.drop_column('checklists', 'data')
    op.drop_column('checklists', 'name')
    op.add_column('destinations', sa.Column('country', sa.String(length=255), nullable=False))
    op.add_column('destinations', sa.Column('country_code', sa.String(length=10), nullable=False))
    op.add_column('destinations', sa.Column('image', sa.String(length=500), nullable=True))
    op.add_column('destinations', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('destinations', sa.Column('language', sa.String(length=100), nullable=True))
    op.add_column('destinations', sa.Column('timezone', sa.String(length=100), nullable=True))
    op.add_column('destinations', sa.Column('best_time', sa.Text(), nullable=True))
    op.add_column('destinations', sa.Column('average_daily_cost', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('destinations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('destinations', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_destinations_name'), table_name='destinations')
    op.add_column('documents', sa.Column('trip_id', sa.BigInteger(), nullable=False))
    op.add_column('documents', sa.Column('type', sa.String(length=100), nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=False))
    op.add_column('documents', sa.Column('expires_at', sa.Date(), nullable=True))
    op.alter_column('documents', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_documents_name'), table_name='documents')
    op.create_index(op.f('ix_documents_trip_id'), 'documents', ['trip_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'trips', ['trip_id'], ['id'])
    op.drop_column('documents', 'description')
    op.drop_column('documents', 'data')
    op.add_column('expenses', sa.Column('trip_id', sa.BigInteger(), nullable=False))
    op.add_column('expenses', sa.Column('budget_category_id', sa.BigInteger(), nullable=False))
    op.add_column('expenses', sa.Column('expense_date', sa.Date(), nullable=False))
    op.add_column('expenses', sa.Column('payment_method', sa.String(length=100), nullable=True))
    op.alter_column('expenses', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('expenses', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('expenses', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('expenses', 'currency',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_expenses_name'), table_name='expenses')
    op.create_index(op.f('ix_expenses_budget_category_id'), 'expenses', ['budget_category_id'], unique=False)
    op.create_index(op.f('ix_expenses_trip_id'), 'expenses', ['trip_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'budget_categories', ['budget_category_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'trips', ['trip_id'], ['id'])
    op.drop_column('expenses', 'category')
    op.drop_column('expenses', 'data')
    op.drop_column('expenses', 'spent_on')
    op.drop_column('expenses', 'name')
    op.add_column('memories', sa.Column('trip_id', sa.BigInteger(), nullable=False))
    op.add_column('memories', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('memories', sa.Column('memory_date', sa.Date(), nullable=False))
    op.add_column('memories', sa.Column('location', sa.String(length=255), nullable=True))
    op.alter_column('memories', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('memories', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index(op.f('ix_memories_name'), table_name='memories')
    op.create_index(op.f('ix_memories_trip_id'), 'memories', ['trip_id'], unique=False)
    op.create_foreign_key(None, 'memories', 'trips', ['trip_id'], ['id'])
    op.drop_column('memories', 'data')
    op.drop_column('memories', 'name')
    op.add_column('notifications', sa.Column('trip_id', sa.BigInteger(), nullable=True))
    op.add_column('notifications', sa.Column('reminder_id', sa.BigInteger(), nullable=True))
    op.add_column('notifications', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('notifications', sa.Column('message', sa.Text(), nullable=False))
    op.add_column('notifications', sa.Column('type', sa.String(length=100), nullable=False))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.alter_column('notifications', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index(op.f('ix_notifications_name'), table_name='notifications')
    op.create_index(op.f('ix_notifications_reminder_id'), 'notifications', ['reminder_id'], unique=False)
    op.create_index(op.f('ix_notifications_trip_id'), 'notifications', ['trip_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'reminders', ['reminder_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'trips', ['trip_id'], ['id'])
    op.drop_column('notifications', 'description')
    op.drop_column('notifications', 'data')
    op.drop_column('notifications', 'name')
    op.add_column('places', sa.Column('destination_id', sa.BigInteger(), nullable=False))
    op.add_column('places', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('places', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('places', sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('places', sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('places', sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('places', sa.Column('opening_time', sa.Time(), nullable=True))
    op.add_column('places', sa.Column('closing_time', sa.Time(), nullable=True))
    op.add_column('places', sa.Column('best_time_to_visit', sa.String(length=100), nullable=True))
    op.add_column('places', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('places', sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('places', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='place_status'), nullable=False))
    op.add_column('places', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('places', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('places', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_places_name'), table_name='places')
    op.drop_index(op.f('ix_places_user_id'), table_name='places')
    op.create_index(op.f('ix_places_destination_id'), 'places', ['destination_id'], unique=False)
    op.drop_constraint(op.f('places_user_id_fkey'), 'places', type_='foreignkey')
    op.create_foreign_key(None, 'places', 'destinations', ['destination_id'], ['id'])
    op.drop_column('places', 'user_id')
    op.drop_column('places', 'data')
    op.add_column('reminders', sa.Column('trip_id', sa.BigInteger(), nullable=False))
    op.add_column('reminders', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('reminders', sa.Column('due_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('reminders', sa.Column('type', sa.Enum('BOOKING', 'PAYMENT', 'DOCUMENT', 'ACTIVITY', 'PACKING', 'FLIGHT', 'CUSTOM', name='reminder_type'), nullable=False))
    op.add_column('reminders', sa.Column('status', sa.Enum(name='reminder_status'), nullable=False))
    op.alter_column('reminders', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('reminders', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index(op.f('ix_reminders_name'), table_name='reminders')
    op.create_index(op.f('ix_reminders_trip_id'), 'reminders', ['trip_id'], unique=False)
    op.create_foreign_key(None, 'reminders', 'trips', ['trip_id'], ['id'])
    op.drop_column('reminders', 'data')
    op.drop_column('reminders', 'name')
    op.add_column('saved_places', sa.Column('place_id', sa.BigInteger(), nullable=False))
    op.alter_column('saved_places', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('saved_places', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index(op.f('ix_saved_places_name'), table_name='saved_places')
    op.create_index(op.f('ix_saved_places_place_id'), 'saved_places', ['place_id'], unique=False)
    op.create_unique_constraint('uq_saved_place_user_place', 'saved_places', ['user_id', 'place_id'])
    op.create_foreign_key(None, 'saved_places', 'places', ['place_id'], ['id'])
    op.drop_column('saved_places', 'description')
    op.drop_column('saved_places', 'data')
    op.drop_column('saved_places', 'name')
    op.add_column('screenshots', sa.Column('trip_id', sa.BigInteger(), nullable=False))
    op.add_column('screenshots', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('screenshots', sa.Column('type', sa.Enum('FLIGHT', 'HOTEL', 'TICKET', 'TRANSPORT', 'PLACE', 'PRICE', 'MAP', 'BOOKING', 'OTHER', name='screenshot_type'), nullable=False))
    op.add_column('screenshots', sa.Column('image_path', sa.String(length=500), nullable=False))
    op.add_column('screenshots', sa.Column('extracted_data', sa.JSON(), nullable=True))
    op.alter_column('screenshots', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('screenshots', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index(op.f('ix_screenshots_name'), table_name='screenshots')
    op.create_index(op.f('ix_screenshots_trip_id'), 'screenshots', ['trip_id'], unique=False)
    op.create_foreign_key(None, 'screenshots', 'trips', ['trip_id'], ['id'])
    op.drop_column('screenshots', 'description')
    op.drop_column('screenshots', 'data')
    op.drop_column('screenshots', 'name')
    op.add_column('transports', sa.Column('trip_id', sa.BigInteger(), nullable=False))
    op.add_column('transports', sa.Column('type', sa.Enum('FLIGHT', 'TRAIN', 'BUS', 'TAXI', 'BOAT', 'OTHER', name='transport_type'), nullable=False))
    op.add_column('transports', sa.Column('provider', sa.String(length=255), nullable=True))
    op.add_column('transports', sa.Column('from_location', sa.String(length=255), nullable=False))
    op.add_column('transports', sa.Column('to_location', sa.String(length=255), nullable=False))
    op.add_column('transports', sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('transports', sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('transports', sa.Column('booking_number', sa.String(length=255), nullable=True))
    op.add_column('transports', sa.Column('seat', sa.String(length=50), nullable=True))
    op.add_column('transports', sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('transports', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('transports', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_transports_name'), table_name='transports')
    op.drop_index(op.f('ix_transports_user_id'), table_name='transports')
    op.create_index(op.f('ix_transports_trip_id'), 'transports', ['trip_id'], unique=False)
    op.drop_constraint(op.f('transports_user_id_fkey'), 'transports', type_='foreignkey')
    op.create_foreign_key(None, 'transports', 'trips', ['trip_id'], ['id'])
    op.drop_column('transports', 'created_at')
    op.drop_column('transports', 'user_id')
    op.drop_column('transports', 'name')
    op.drop_column('transports', 'description')
    op.drop_column('transports', 'data')
    op.add_column('trips', sa.Column('destination_id', sa.BigInteger(), nullable=False))
    op.add_column('trips', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('trips', sa.Column('budget_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('trips', sa.Column('cover_image', sa.String(length=500), nullable=True))
    op.add_column('trips', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('trips', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('trips', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('trips', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('trips', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('trips', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('trips', 'status',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.Enum('PLANNING', 'UPCOMING', 'ONGOING', 'COMPLETED', 'CANCELLED', name='trip_status'),
               existing_nullable=False)
    op.drop_index(op.f('ix_trips_name'), table_name='trips')
    op.create_index(op.f('ix_trips_destination_id'), 'trips', ['destination_id'], unique=False)
    op.create_foreign_key(None, 'trips', 'destinations', ['destination_id'], ['id'])
    op.drop_column('trips', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_index(op.f('ix_trips_destination_id'), table_name='trips')
    op.create_index(op.f('ix_trips_name'), 'trips', ['name'], unique=False)
    op.alter_column('trips', 'status',
               existing_type=sa.Enum('PLANNING', 'UPCOMING', 'ONGOING', 'COMPLETED', 'CANCELLED', name='trip_status'),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.alter_column('trips', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('trips', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('trips', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('trips', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('trips', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('trips', 'updated_at')
    op.drop_column('trips', 'cover_image')
    op.drop_column('trips', 'budget_amount')
    op.drop_column('trips', 'currency')
    op.drop_column('trips', 'destination_id')
    op.add_column('transports', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('transports', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('transports', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('transports', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transports', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'transports', type_='foreignkey')
    op.create_foreign_key(op.f('transports_user_id_fkey'), 'transports', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_transports_trip_id'), table_name='transports')
    op.create_index(op.f('ix_transports_user_id'), 'transports', ['user_id'], unique=False)
    op.create_index(op.f('ix_transports_name'), 'transports', ['name'], unique=False)
    op.alter_column('transports', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('transports', 'notes')
    op.drop_column('transports', 'cost')
    op.drop_column('transports', 'seat')
    op.drop_column('transports', 'booking_number')
    op.drop_column('transports', 'arrival_time')
    op.drop_column('transports', 'departure_time')
    op.drop_column('transports', 'to_location')
    op.drop_column('transports', 'from_location')
    op.drop_column('transports', 'provider')
    op.drop_column('transports', 'type')
    op.drop_column('transports', 'trip_id')
    op.add_column('screenshots', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('screenshots', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('screenshots', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'screenshots', type_='foreignkey')
    op.drop_index(op.f('ix_screenshots_trip_id'), table_name='screenshots')
    op.create_index(op.f('ix_screenshots_name'), 'screenshots', ['name'], unique=False)
    op.alter_column('screenshots', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('screenshots', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('screenshots', 'extracted_data')
    op.drop_column('screenshots', 'image_path')
    op.drop_column('screenshots', 'type')
    op.drop_column('screenshots', 'title')
    op.drop_column('screenshots', 'trip_id')
    op.add_column('saved_places', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('saved_places', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('saved_places', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'saved_places', type_='foreignkey')
    op.drop_constraint('uq_saved_place_user_place', 'saved_places', type_='unique')
    op.drop_index(op.f('ix_saved_places_place_id'), table_name='saved_places')
    op.create_index(op.f('ix_saved_places_name'), 'saved_places', ['name'], unique=False)
    op.alter_column('saved_places', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('saved_places', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('saved_places', 'place_id')
    op.add_column('reminders', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('reminders', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.drop_index(op.f('ix_reminders_trip_id'), table_name='reminders')
    op.create_index(op.f('ix_reminders_name'), 'reminders', ['name'], unique=False)
    op.alter_column('reminders', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('reminders', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('reminders', 'status')
    op.drop_column('reminders', 'type')
    op.drop_column('reminders', 'due_date')
    op.drop_column('reminders', 'title')
    op.drop_column('reminders', 'trip_id')
    op.add_column('places', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('places', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'places', type_='foreignkey')
    op.create_foreign_key(op.f('places_user_id_fkey'), 'places', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_places_destination_id'), table_name='places')
    op.create_index(op.f('ix_places_user_id'), 'places', ['user_id'], unique=False)
    op.create_index(op.f('ix_places_name'), 'places', ['name'], unique=False)
    op.alter_column('places', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('places', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('places', 'updated_at')
    op.drop_column('places', 'status')
    op.drop_column('places', 'rating')
    op.drop_column('places', 'website')
    op.drop_column('places', 'best_time_to_visit')
    op.drop_column('places', 'closing_time')
    op.drop_column('places', 'opening_time')
    op.drop_column('places', 'estimated_cost')
    op.drop_column('places', 'longitude')
    op.drop_column('places', 'latitude')
    op.drop_column('places', 'address')
    op.drop_column('places', 'category')
    op.drop_column('places', 'destination_id')
    op.add_column('notifications', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_trip_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_reminder_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_name'), 'notifications', ['name'], unique=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'reminder_id')
    op.drop_column('notifications', 'trip_id')
    op.add_column('memories', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('memories', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_index(op.f('ix_memories_trip_id'), table_name='memories')
    op.create_index(op.f('ix_memories_name'), 'memories', ['name'], unique=False)
    op.alter_column('memories', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('memories', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('memories', 'location')
    op.drop_column('memories', 'memory_date')
    op.drop_column('memories', 'title')
    op.drop_column('memories', 'trip_id')
    op.add_column('expenses', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('expenses', sa.Column('spent_on', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('expenses', sa.Column('category', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_trip_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_budget_category_id'), table_name='expenses')
    op.create_index(op.f('ix_expenses_name'), 'expenses', ['name'], unique=False)
    op.alter_column('expenses', 'currency',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('expenses', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('expenses', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('expenses', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('expenses', 'payment_method')
    op.drop_column('expenses', 'expense_date')
    op.drop_column('expenses', 'budget_category_id')
    op.drop_column('expenses', 'trip_id')
    op.add_column('documents', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_trip_id'), table_name='documents')
    op.create_index(op.f('ix_documents_name'), 'documents', ['name'], unique=False)
    op.alter_column('documents', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('documents', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('documents', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('documents', 'expires_at')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'type')
    op.drop_column('documents', 'trip_id')
    op.create_index(op.f('ix_destinations_name'), 'destinations', ['name'], unique=False)
    op.alter_column('destinations', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('destinations', 'updated_at')
    op.drop_column('destinations', 'average_daily_cost')
    op.drop_column('destinations', 'best_time')
    op.drop_column('destinations', 'timezone')
    op.drop_column('destinations', 'language')
    op.drop_column('destinations', 'currency')
    op.drop_column('destinations', 'image')
    op.drop_column('destinations', 'country_code')
    op.drop_column('destinations', 'country')
    op.add_column('checklists', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('checklists', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('checklists', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('checklists', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'checklists', type_='foreignkey')
    op.create_foreign_key(op.f('checklists_user_id_fkey'), 'checklists', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_checklists_trip_id'), table_name='checklists')
    op.create_index(op.f('ix_checklists_user_id'), 'checklists', ['user_id'], unique=False)
    op.create_index(op.f('ix_checklists_name'), 'checklists', ['name'], unique=False)
    op.alter_column('checklists', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('checklists', 'title')
    op.drop_column('checklists', 'trip_id')
    op.add_column('budgets', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('budgets', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('budgets', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('budgets', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('budgets', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.create_foreign_key(op.f('budgets_user_id_fkey'), 'budgets', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_budgets_trip_id'), table_name='budgets')
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_index(op.f('ix_budgets_name'), 'budgets', ['name'], unique=False)
    op.alter_column('budgets', 'currency',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    op.alter_column('budgets', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('budgets', 'updated_at')
    op.drop_column('budgets', 'spent_amount')
    op.drop_column('budgets', 'saved_amount')
    op.drop_column('budgets', 'total_budget')
    op.drop_column('budgets', 'trip_id')
    op.add_column('accommodations', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('accommodations', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('accommodations', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('accommodations', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'accommodations', type_='foreignkey')
    op.create_foreign_key(op.f('accommodations_user_id_fkey'), 'accommodations', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_accommodations_trip_id'), table_name='accommodations')
    op.create_index(op.f('ix_accommodations_user_id'), 'accommodations', ['user_id'], unique=False)
    op.create_index(op.f('ix_accommodations_name'), 'accommodations', ['name'], unique=False)
    op.alter_column('accommodations', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('accommodations', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('accommodations', 'notes')
    op.drop_column('accommodations', 'cost')
    op.drop_column('accommodations', 'confirmation_number')
    op.drop_column('accommodations', 'room_type')
    op.drop_column('accommodations', 'check_out')
    op.drop_column('accommodations', 'check_in')
    op.drop_column('accommodations', 'address')
    op.drop_column('accommodations', 'trip_id')
    op.drop_index(op.f('ix_expense_splits_user_id'), table_name='expense_splits')
    op.drop_index(op.f('ix_expense_splits_id'), table_name='expense_splits')
    op.drop_index(op.f('ix_expense_splits_expense_id'), table_name='expense_splits')
    op.drop_table('expense_splits')
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_user_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_memory_photos_memory_id'), table_name='memory_photos')
    op.drop_index(op.f('ix_memory_photos_id'), table_name='memory_photos')
    op.drop_table('memory_photos')
    op.drop_index(op.f('ix_itinerary_items_place_id'), table_name='itinerary_items')
    op.drop_index(op.f('ix_itinerary_items_itinerary_day_id'), table_name='itinerary_items')
    op.drop_index(op.f('ix_itinerary_items_id'), table_name='itinerary_items')
    op.drop_table('itinerary_items')
    op.drop_index(op.f('ix_checklist_items_id'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_checklist_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_budget_categories_id'), table_name='budget_categories')
    op.drop_index(op.f('ix_budget_categories_budget_id'), table_name='budget_categories')
    op.drop_table('budget_categories')
    op.drop_index(op.f('ix_ai_messages_id'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_ai_extractions_user_id'), table_name='ai_extractions')
    op.drop_index(op.f('ix_ai_extractions_trip_id'), table_name='ai_extractions')
    op.drop_index(op.f('ix_ai_extractions_screenshot_id'), table_name='ai_extractions')
    op.drop_index(op.f('ix_ai_extractions_id'), table_name='ai_extractions')
    op.drop_index(op.f('ix_ai_extractions_document_id'), table_name='ai_extractions')
    op.drop_table('ai_extractions')
    op.drop_index(op.f('ix_trip_wallets_trip_id'), table_name='trip_wallets')
    op.drop_index(op.f('ix_trip_wallets_id'), table_name='trip_wallets')
    op.drop_table('trip_wallets')
    op.drop_index(op.f('ix_trip_members_user_id'), table_name='trip_members')
    op.drop_index(op.f('ix_trip_members_trip_id'), table_name='trip_members')
    op.drop_index(op.f('ix_trip_members_id'), table_name='trip_members')
    op.drop_table('trip_members')
    op.drop_index(op.f('ix_place_tips_place_id'), table_name='place_tips')
    op.drop_index(op.f('ix_place_tips_id'), table_name='place_tips')
    op.drop_table('place_tips')
    op.drop_index(op.f('ix_place_photos_place_id'), table_name='place_photos')
    op.drop_index(op.f('ix_place_photos_id'), table_name='place_photos')
    op.drop_table('place_photos')
    op.drop_index(op.f('ix_packing_lists_trip_id'), table_name='packing_lists')
    op.drop_index(op.f('ix_packing_lists_id'), table_name='packing_lists')
    op.drop_table('packing_lists')
    op.drop_index(op.f('ix_itinerary_days_trip_id'), table_name='itinerary_days')
    op.drop_index(op.f('ix_itinerary_days_id'), table_name='itinerary_days')
    op.drop_table('itinerary_days')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_trip_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
