"""update budget tables

Revision ID: 61eb90155a05
Revises: 343bdbf5a71d
Create Date: 2026-09-29 14:10:14.862500
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '61eb90155a05'
down_revision: Union[str, None] = '343bdbf5a71d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_destinations_name'), 'destinations', ['name'], unique=False)
    op.alter_column('users', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_destinations_name'), table_name='destinations')
    # ### end Alembic commands ###